import type { WorkoutDay, WorkoutExercise } from "@/lib/types";

const variant = (
  name: string,
  angle: string,
  equipment: string,
  jointStress: "low" | "moderate" | "high" = "moderate",
) => ({ name, angle, equipment, jointStress });

const exercise = (
  input: Omit<
    WorkoutExercise,
    "secondary" | "previousBest" | "formTip" | "mistake"
  > &
    Partial<
      Pick<
        WorkoutExercise,
        "secondary" | "previousBest" | "formTip" | "mistake"
      >
    >,
): WorkoutExercise => ({
  secondary: [],
  previousBest: `${input.lastWeight} kg × ${input.repMin + 2}`,
  formTip: "Control the lowering phase and keep every working rep repeatable.",
  mistake: "Avoid trading range of motion for extra load.",
  ...input,
});

export const workoutPlan: WorkoutDay[] = [
  {
    key: "monday",
    day: "Monday",
    shortDay: "M",
    title: "Chest + Triceps",
    focus: "Upper chest strength · triceps",
    duration: 82,
    intensity: "Build",
    warmup: [
      "Push-ups · 2 sets × 10–15, stop well before fatigue",
      "Incline press ramp-up · 2 light sets",
      "Cable external rotations · 12 per side",
    ],
    exercises: [
      exercise({
        id: "incline-db-press",
        name: "Incline Dumbbell Press",
        target: "Upper chest",
        secondary: ["Front delts", "Triceps"],
        movement: "Horizontal press",
        focus: "30° incline · clavicular fibers",
        equipment: "Dumbbells",
        sets: 4,
        repMin: 6,
        repMax: 10,
        rest: 150,
        lastWeight: 24,
        kind: "main",
        goal: "strength",
        reason: "Your anchor lift is trending up. Keep it stable through week 5.",
        formTip: "Set the bench near 30° and finish with wrists stacked over elbows.",
        mistake: "A steep bench shifts work from upper chest to front delts.",
        variants: [
          variant("Incline Barbell Press", "30° upper chest", "Barbell", "high"),
          variant("Incline Smith Press", "Stable upper chest press", "Smith machine"),
          variant("Incline Machine Press", "Supported upper chest", "Machine", "low"),
        ],
      }),
      exercise({
        id: "machine-chest-press",
        name: "Machine Chest Press",
        target: "Mid chest",
        secondary: ["Triceps"],
        movement: "Horizontal press",
        focus: "Mid chest · stable tension",
        equipment: "Machine",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 120,
        lastWeight: 45,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Stable press after the free-weight anchor keeps output high.",
        variants: [
          variant("Flat Dumbbell Press", "Mid chest · stability", "Dumbbells"),
          variant("Smith Machine Bench Press", "Mid chest · fixed path", "Smith machine"),
          variant("Flat Barbell Bench Press", "Mid chest · strength", "Barbell", "high"),
        ],
      }),
      exercise({
        id: "low-high-cable-fly",
        name: "Low-to-High Cable Fly",
        target: "Upper chest",
        movement: "Chest adduction",
        focus: "Low-to-high · shortened position",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 75,
        lastWeight: 10,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "Rotated in this week for upper-chest angle coverage and low joint stress.",
        variants: [
          variant("Pec Deck Fly", "Mid chest · deep stretch", "Machine", "low"),
          variant("Cable Fly", "Mid chest · constant tension", "Cable", "low"),
          variant("Dumbbell Fly", "Chest stretch", "Dumbbells", "moderate"),
          variant("High-to-Low Cable Fly", "Lower chest", "Cable", "low"),
        ],
      }),
      exercise({
        id: "rope-pushdown",
        name: "Rope Triceps Pushdown",
        target: "Lateral triceps",
        movement: "Elbow extension",
        focus: "Shortened triceps · squeeze",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 75,
        lastWeight: 22.5,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Pairs low joint stress with the pressing volume already completed.",
        variants: [
          variant("Straight Bar Pushdown", "Heavy shortened triceps", "Cable"),
          variant("V-Bar Pushdown", "Neutral-grip triceps", "Cable", "low"),
        ],
      }),
      exercise({
        id: "overhead-cable-extension",
        name: "Overhead Cable Extension",
        target: "Long-head triceps",
        movement: "Elbow extension",
        focus: "Overhead · loaded stretch",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 14,
        rest: 75,
        lastWeight: 17.5,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "Complements pushdowns by training the long head at long muscle length.",
        variants: [
          variant("Overhead Dumbbell Extension", "Long-head stretch", "Dumbbell"),
          variant("Skull Crushers", "Stretched triceps", "EZ bar", "high"),
        ],
      }),
      exercise({
        id: "cable-squeeze-press",
        name: "Cable Squeeze Press",
        target: "Inner chest",
        movement: "Horizontal press",
        focus: "Adduction · finisher",
        equipment: "Cable",
        sets: 2,
        repMin: 12,
        repMax: 15,
        rest: 60,
        lastWeight: 12.5,
        kind: "isolation",
        goal: "pump",
        reason: "Two efficient finish sets bring the session to 18 working sets.",
        variants: [
          variant("Plate Squeeze Press", "Chest squeeze", "Plate", "low"),
          variant("Push-up Plus", "Chest finisher", "Bodyweight", "low"),
        ],
      }),
    ],
  },
  {
    key: "tuesday",
    day: "Tuesday",
    shortDay: "T",
    title: "Back + Biceps",
    focus: "Lat width · back thickness",
    duration: 86,
    intensity: "Heavy",
    warmup: [
      "Pull-ups · 3 sets × 5, leave 3 reps in reserve",
      "Scapular pulldowns · 2 sets × 10",
      "One light row ramp-up set",
    ],
    exercises: [
      exercise({
        id: "wide-lat-pulldown",
        name: "Wide-Grip Lat Pulldown",
        target: "Lats",
        secondary: ["Biceps", "Upper back"],
        movement: "Vertical pull",
        focus: "Lat width · frontal plane",
        equipment: "Cable",
        sets: 4,
        repMin: 6,
        repMax: 10,
        rest: 135,
        lastWeight: 50,
        kind: "main",
        goal: "strength",
        reason: "Primary vertical pull stays locked for this strength block.",
        variants: [
          variant("Neutral-Grip Pulldown", "Lats · shoulder friendly", "Cable", "low"),
          variant("Assisted Pull-up", "Vertical pull · body control", "Machine"),
          variant("Close-Grip Pulldown", "Lower lats", "Cable", "low"),
        ],
      }),
      exercise({
        id: "seated-cable-row",
        name: "Seated Cable Row",
        target: "Mid back",
        secondary: ["Lats", "Biceps"],
        movement: "Horizontal pull",
        focus: "Back thickness · neutral grip",
        equipment: "Cable",
        sets: 4,
        repMin: 8,
        repMax: 12,
        rest: 120,
        lastWeight: 45,
        kind: "main",
        goal: "hypertrophy",
        reason: "Repeatable setup makes week-to-week overload easy to measure.",
        variants: [
          variant("Chest-Supported Row", "Upper-back thickness", "Machine", "low"),
          variant("T-Bar Row", "Mid-back strength", "Barbell", "high"),
          variant("Machine Row", "Stable back thickness", "Machine", "low"),
        ],
      }),
      exercise({
        id: "single-arm-db-row",
        name: "Single-Arm Dumbbell Row",
        target: "Lats",
        movement: "Horizontal pull",
        focus: "Unilateral · lower lat",
        equipment: "Dumbbell",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 90,
        lastWeight: 28,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Unilateral work balances sides without adding another fixed machine.",
        variants: [
          variant("Single-Arm Cable Row", "Unilateral · constant tension", "Cable", "low"),
          variant("Meadows Row", "Upper lat · stretch", "Landmine", "high"),
        ],
      }),
      exercise({
        id: "straight-arm-pulldown",
        name: "Straight-Arm Pulldown",
        target: "Lats",
        movement: "Shoulder extension",
        focus: "Lat isolation · shortened",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 75,
        lastWeight: 22.5,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "Adds lat volume with almost no biceps fatigue.",
        variants: [
          variant("Cable Pullover", "Lats · long range", "Cable", "low"),
          variant("Machine Pullover", "Lats · stable path", "Machine", "low"),
        ],
      }),
      exercise({
        id: "reverse-pec-deck",
        name: "Reverse Pec Deck",
        target: "Rear delts",
        secondary: ["Upper back"],
        movement: "Horizontal abduction",
        focus: "Rear delts · supported",
        equipment: "Machine",
        sets: 3,
        repMin: 12,
        repMax: 15,
        rest: 60,
        lastWeight: 25,
        kind: "isolation",
        goal: "pump",
        reason: "Low-fatigue upper-back work supports shoulder balance.",
        variants: [
          variant("Face Pull", "Rear delts · external rotation", "Cable", "low"),
          variant("Rear Delt Fly", "Rear delts", "Dumbbells", "low"),
        ],
      }),
      exercise({
        id: "ez-bar-curl",
        name: "EZ-Bar Curl",
        target: "Biceps",
        movement: "Elbow flexion",
        focus: "Heavy curl · mid-range",
        equipment: "EZ bar",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 90,
        lastWeight: 22.5,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Stable heavy curl slot anchors direct biceps progression.",
        variants: [
          variant("Barbell Curl", "Heavy biceps", "Barbell", "high"),
          variant("Cable Curl", "Constant-tension biceps", "Cable", "low"),
          variant("Preacher Curl", "Shortened biceps", "Machine"),
        ],
      }),
      exercise({
        id: "hammer-curl",
        name: "Hammer Curl",
        target: "Brachialis",
        secondary: ["Forearms", "Biceps"],
        movement: "Neutral-grip curl",
        focus: "Arm thickness · neutral grip",
        equipment: "Dumbbells",
        sets: 2,
        repMin: 10,
        repMax: 14,
        rest: 75,
        lastWeight: 12,
        kind: "isolation",
        goal: "pump",
        reason: "Neutral grip finishes arms while spreading stress across the elbow flexors.",
        variants: [
          variant("Rope Hammer Curl", "Neutral grip · cable", "Cable", "low"),
          variant("Cross-Body Hammer Curl", "Brachialis", "Dumbbells", "low"),
        ],
      }),
    ],
  },
  {
    key: "wednesday",
    day: "Wednesday",
    shortDay: "W",
    title: "Shoulders + Arms",
    focus: "Delts · arm detail",
    duration: 78,
    intensity: "Volume",
    warmup: [
      "Push-ups · 2 sets × 10",
      "Pull-ups · 2 sets × 5",
      "Cable external rotations · 12 per side",
    ],
    exercises: [
      exercise({
        id: "seated-db-shoulder-press",
        name: "Seated Dumbbell Shoulder Press",
        target: "Front delts",
        secondary: ["Triceps", "Side delts"],
        movement: "Vertical press",
        focus: "Overhead strength",
        equipment: "Dumbbells",
        sets: 4,
        repMin: 6,
        repMax: 10,
        rest: 150,
        lastWeight: 18,
        kind: "main",
        goal: "strength",
        reason: "The block’s stable overhead strength marker.",
        variants: [
          variant("Machine Shoulder Press", "Stable overhead press", "Machine", "low"),
          variant("Smith Shoulder Press", "Fixed overhead path", "Smith machine"),
          variant("Arnold Press", "Front and side delts", "Dumbbells", "high"),
        ],
      }),
      exercise({
        id: "lean-away-lateral-raise",
        name: "Lean-Away Cable Lateral Raise",
        target: "Side delts",
        movement: "Shoulder abduction",
        focus: "Lengthened side delt",
        equipment: "Cable",
        sets: 3,
        repMin: 12,
        repMax: 16,
        rest: 60,
        lastWeight: 7.5,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "This week’s side-delt rotation loads the lengthened range.",
        variants: [
          variant("Dumbbell Lateral Raise", "Side delt · mid-range", "Dumbbells", "low"),
          variant("Machine Lateral Raise", "Stable side delt", "Machine", "low"),
          variant("Cable Lateral Raise", "Constant-tension side delt", "Cable", "low"),
        ],
      }),
      exercise({
        id: "face-pull",
        name: "Face Pull",
        target: "Rear delts",
        secondary: ["Rotator cuff", "Upper back"],
        movement: "Horizontal pull",
        focus: "Rear delts · external rotation",
        equipment: "Cable",
        sets: 3,
        repMin: 12,
        repMax: 16,
        rest: 60,
        lastWeight: 17.5,
        kind: "isolation",
        goal: "joint relief",
        reason: "Balances pressing with a shoulder-friendly rear-delt slot.",
        variants: [
          variant("Reverse Pec Deck", "Rear delts · supported", "Machine", "low"),
          variant("Rear Delt Fly", "Rear delts", "Dumbbells", "low"),
        ],
      }),
      exercise({
        id: "dumbbell-shrug",
        name: "Dumbbell Shrug",
        target: "Upper traps",
        movement: "Scapular elevation",
        focus: "Trap thickness",
        equipment: "Dumbbells",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 75,
        lastWeight: 30,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Direct trap work without loading the lower back.",
        variants: [
          variant("Machine Shrug", "Supported traps", "Machine", "low"),
          variant("Barbell Shrug", "Heavy traps", "Barbell", "high"),
        ],
      }),
      exercise({
        id: "skull-crusher",
        name: "EZ-Bar Skull Crusher",
        target: "Triceps",
        movement: "Elbow extension",
        focus: "Long-head stretch",
        equipment: "EZ bar",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 90,
        lastWeight: 17.5,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Placed away from heavy chest day to manage elbow stress.",
        variants: [
          variant("Overhead Cable Extension", "Long-head stretch", "Cable", "low"),
          variant("Rope Pushdown", "Shortened triceps", "Cable", "low"),
        ],
      }),
      exercise({
        id: "incline-db-curl",
        name: "Incline Dumbbell Curl",
        target: "Biceps long head",
        movement: "Elbow flexion",
        focus: "Lengthened biceps",
        equipment: "Dumbbells",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 75,
        lastWeight: 10,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Lengthened curl complements Tuesday’s mid-range heavy curl.",
        variants: [
          variant("Bayesian Cable Curl", "Lengthened biceps", "Cable", "low"),
          variant("Preacher Curl", "Shortened biceps", "Machine"),
        ],
      }),
      exercise({
        id: "cable-curl",
        name: "Cable Curl",
        target: "Biceps",
        movement: "Elbow flexion",
        focus: "Constant tension · squeeze",
        equipment: "Cable",
        sets: 2,
        repMin: 12,
        repMax: 15,
        rest: 60,
        lastWeight: 15,
        kind: "isolation",
        goal: "pump",
        reason: "Two low-fatigue pump sets close the session inside the volume cap.",
        variants: [
          variant("Spider Curl", "Shortened biceps", "Dumbbells"),
          variant("Machine Curl", "Stable biceps", "Machine", "low"),
        ],
      }),
    ],
  },
  {
    key: "thursday",
    day: "Thursday",
    shortDay: "T",
    title: "Chest + Back",
    focus: "Heavy opposing compounds",
    duration: 88,
    intensity: "Heavy",
    warmup: [
      "Push-ups · 2 sets × 10",
      "Pull-ups · 2 sets × 5",
      "One light press + row ramp-up superset",
    ],
    exercises: [
      exercise({
        id: "flat-db-press",
        name: "Flat Dumbbell Press",
        target: "Mid chest",
        secondary: ["Triceps"],
        movement: "Horizontal press",
        focus: "Mid chest · strength",
        equipment: "Dumbbells",
        sets: 4,
        repMin: 6,
        repMax: 10,
        rest: 150,
        lastWeight: 26,
        kind: "main",
        goal: "strength",
        reason: "Stable Thursday press for clean overload tracking.",
        variants: [
          variant("Machine Chest Press", "Mid chest · stable", "Machine", "low"),
          variant("Smith Bench Press", "Mid chest · fixed path", "Smith machine"),
        ],
      }),
      exercise({
        id: "close-grip-pulldown",
        name: "Close-Grip Lat Pulldown",
        target: "Lower lats",
        secondary: ["Biceps"],
        movement: "Vertical pull",
        focus: "Sagittal pull · lower lats",
        equipment: "Cable",
        sets: 4,
        repMin: 8,
        repMax: 12,
        rest: 120,
        lastWeight: 47.5,
        kind: "main",
        goal: "hypertrophy",
        reason: "Different grip from Tuesday covers the lats without repeating the same angle.",
        variants: [
          variant("Neutral-Grip Pulldown", "Lats · shoulder friendly", "Cable", "low"),
          variant("Assisted Chin-up", "Lower lats · biceps", "Machine"),
        ],
      }),
      exercise({
        id: "incline-machine-press",
        name: "Incline Machine Press",
        target: "Upper chest",
        movement: "Horizontal press",
        focus: "Supported upper chest",
        equipment: "Machine",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 105,
        lastWeight: 40,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Machine support limits fatigue after the heavy dumbbell press.",
        variants: [
          variant("Incline Smith Press", "Upper chest · fixed path", "Smith machine"),
          variant("Low-to-High Cable Press", "Upper chest · constant tension", "Cable", "low"),
        ],
      }),
      exercise({
        id: "chest-supported-row",
        name: "Chest-Supported Row",
        target: "Mid back",
        secondary: ["Rear delts", "Lats"],
        movement: "Horizontal pull",
        focus: "Upper-back thickness",
        equipment: "Machine",
        sets: 4,
        repMin: 8,
        repMax: 12,
        rest: 120,
        lastWeight: 42.5,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Chest support keeps the lower back fresh for Saturday’s RDL.",
        variants: [
          variant("Wide-Grip Cable Row", "Upper back", "Cable", "low"),
          variant("Machine Row", "Mid back · stable", "Machine", "low"),
        ],
      }),
      exercise({
        id: "pec-deck",
        name: "Pec Deck Fly",
        target: "Chest",
        movement: "Chest adduction",
        focus: "Deep stretch · stable",
        equipment: "Machine",
        sets: 3,
        repMin: 12,
        repMax: 15,
        rest: 75,
        lastWeight: 30,
        kind: "isolation",
        goal: "pump",
        reason: "A low-skill fly slot after compounds adds stimulus without more pressing.",
        variants: [
          variant("Low-to-High Cable Fly", "Upper chest", "Cable", "low"),
          variant("Cable Fly", "Mid chest", "Cable", "low"),
        ],
      }),
      exercise({
        id: "wide-seated-row",
        name: "Wide-Grip Seated Row",
        target: "Upper back",
        secondary: ["Rear delts"],
        movement: "Horizontal pull",
        focus: "Elbows out · upper back",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 14,
        rest: 90,
        lastWeight: 37.5,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Elbows-out angle complements the lat-biased pulldown.",
        variants: [
          variant("High Machine Row", "Upper back", "Machine", "low"),
          variant("Rear Delt Row", "Rear delts · upper back", "Dumbbells"),
        ],
      }),
    ],
  },
  {
    key: "friday",
    day: "Friday",
    shortDay: "F",
    title: "Upper Body Hypertrophy",
    focus: "Weak points · quality volume",
    duration: 80,
    intensity: "Volume",
    warmup: [
      "Easy push-ups · 2 sets × 10",
      "Scapular pull-ups · 2 sets × 5",
      "Light lateral raises · 15 reps",
    ],
    exercises: [
      exercise({
        id: "decline-db-press",
        name: "Decline Dumbbell Press",
        target: "Lower chest",
        secondary: ["Triceps"],
        movement: "Horizontal press",
        focus: "Lower chest · low incline",
        equipment: "Dumbbells",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 120,
        lastWeight: 24,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Fresh angle for the week’s third chest exposure, kept below heavy-day volume.",
        variants: [
          variant("High-to-Low Cable Press", "Lower chest", "Cable", "low"),
          variant("Decline Machine Press", "Lower chest · stable", "Machine", "low"),
        ],
      }),
      exercise({
        id: "neutral-lat-pulldown",
        name: "Neutral-Grip Lat Pulldown",
        target: "Lats",
        movement: "Vertical pull",
        focus: "Shoulder-friendly lat work",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 14,
        rest: 105,
        lastWeight: 42.5,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Neutral grip manages fatigue while adding productive lat frequency.",
        variants: [
          variant("Machine Pulldown", "Lats · stable", "Machine", "low"),
          variant("Straight-Arm Pulldown", "Lat isolation", "Cable", "low"),
        ],
      }),
      exercise({
        id: "machine-chest-press-friday",
        name: "Machine Chest Press",
        target: "Mid chest",
        movement: "Horizontal press",
        focus: "Stable chest volume",
        equipment: "Machine",
        sets: 3,
        repMin: 10,
        repMax: 14,
        rest: 90,
        lastWeight: 40,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Stable setup lets you push close to failure safely on the volume day.",
        variants: [
          variant("Cable Chest Press", "Mid chest · constant tension", "Cable", "low"),
          variant("Push-up", "Chest · bodyweight", "Bodyweight", "low"),
        ],
      }),
      exercise({
        id: "cable-row-friday",
        name: "Single-Arm Cable Row",
        target: "Lats",
        movement: "Horizontal pull",
        focus: "Unilateral · controlled stretch",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 14,
        rest: 90,
        lastWeight: 25,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Unilateral cable work is low fatigue and easy to recover from.",
        variants: [
          variant("Machine Row", "Mid back · stable", "Machine", "low"),
          variant("Dumbbell Row", "Lats · free weight", "Dumbbell"),
        ],
      }),
      exercise({
        id: "machine-lateral-raise",
        name: "Machine Lateral Raise",
        target: "Side delts",
        movement: "Shoulder abduction",
        focus: "Stable side-delt tension",
        equipment: "Machine",
        sets: 3,
        repMin: 12,
        repMax: 16,
        rest: 60,
        lastWeight: 20,
        kind: "isolation",
        goal: "pump",
        reason: "Second side-delt exposure uses a stable setup for high-quality reps.",
        variants: [
          variant("Cable Lateral Raise", "Side delts · constant tension", "Cable", "low"),
          variant("Dumbbell Lateral Raise", "Side delts · mid-range", "Dumbbells", "low"),
        ],
      }),
      exercise({
        id: "preacher-curl",
        name: "Preacher Curl",
        target: "Biceps",
        movement: "Elbow flexion",
        focus: "Shortened biceps · strict",
        equipment: "Machine",
        sets: 3,
        repMin: 10,
        repMax: 14,
        rest: 75,
        lastWeight: 17.5,
        kind: "isolation",
        goal: "pump",
        reason: "Strict curl removes momentum late in the training week.",
        variants: [
          variant("Cable Curl", "Constant-tension biceps", "Cable", "low"),
          variant("Hammer Curl", "Brachialis", "Dumbbells", "low"),
        ],
      }),
      exercise({
        id: "overhead-triceps-friday",
        name: "Overhead Rope Extension",
        target: "Long-head triceps",
        movement: "Elbow extension",
        focus: "Long-head stretch",
        equipment: "Cable",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 75,
        lastWeight: 15,
        kind: "isolation",
        goal: "pump",
        reason: "Cable resistance is elbow-friendly for the week’s final arm work.",
        variants: [
          variant("Rope Pushdown", "Shortened triceps", "Cable", "low"),
          variant("Single-Arm Cable Extension", "Unilateral triceps", "Cable", "low"),
        ],
      }),
    ],
  },
  {
    key: "saturday",
    day: "Saturday",
    shortDay: "S",
    title: "Legs + Abs",
    focus: "Complete lower body · core",
    duration: 89,
    intensity: "Build",
    warmup: [
      "Cycle or treadmill · 5–8 minutes easy",
      "Bodyweight squats · 2 sets × 12",
      "Hip hinge drill · 10 controlled reps",
    ],
    exercises: [
      exercise({
        id: "leg-press",
        name: "Leg Press",
        target: "Quads",
        secondary: ["Glutes"],
        movement: "Knee-dominant squat",
        focus: "Quad compound · stable",
        equipment: "Machine",
        sets: 4,
        repMin: 8,
        repMax: 12,
        rest: 150,
        lastWeight: 100,
        kind: "main",
        goal: "strength",
        reason: "Stable lower-body anchor stays fixed for the current block.",
        variants: [
          variant("Hack Squat", "Quad compound", "Machine", "high"),
          variant("Smith Machine Squat", "Quad-biased squat", "Smith machine", "high"),
          variant("Goblet Squat", "Squat pattern · accessible", "Dumbbell", "low"),
        ],
      }),
      exercise({
        id: "romanian-deadlift",
        name: "Romanian Deadlift",
        target: "Hamstrings",
        secondary: ["Glutes", "Spinal erectors"],
        movement: "Hip hinge",
        focus: "Lengthened hamstrings",
        equipment: "Barbell",
        sets: 4,
        repMin: 6,
        repMax: 10,
        rest: 150,
        lastWeight: 50,
        kind: "main",
        goal: "strength",
        reason: "Main hinge is progressing and remains locked through week 5.",
        variants: [
          variant("Dumbbell RDL", "Hamstring hinge", "Dumbbells"),
          variant("Smith RDL", "Stable hamstring hinge", "Smith machine"),
        ],
      }),
      exercise({
        id: "walking-lunge",
        name: "Walking Lunge",
        target: "Quads + glutes",
        movement: "Single-leg squat",
        focus: "Unilateral · stride control",
        equipment: "Dumbbells",
        sets: 3,
        repMin: 8,
        repMax: 12,
        rest: 105,
        lastWeight: 12,
        kind: "accessory",
        goal: "hypertrophy",
        reason: "Single-leg slot supports balance and glute development.",
        variants: [
          variant("Bulgarian Split Squat", "Single-leg · long range", "Dumbbells", "high"),
          variant("Reverse Lunge", "Single-leg · knee friendly", "Dumbbells", "low"),
        ],
      }),
      exercise({
        id: "leg-extension",
        name: "Leg Extension",
        target: "Quads",
        movement: "Knee extension",
        focus: "Shortened quads",
        equipment: "Machine",
        sets: 3,
        repMin: 12,
        repMax: 15,
        rest: 75,
        lastWeight: 35,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "Direct quad work fills the shortened-position gap.",
        variants: [
          variant("Sissy Squat", "Lengthened quads", "Bodyweight", "high"),
          variant("Single-Leg Extension", "Unilateral quads", "Machine", "low"),
        ],
      }),
      exercise({
        id: "seated-leg-curl",
        name: "Seated Leg Curl",
        target: "Hamstrings",
        movement: "Knee flexion",
        focus: "Lengthened hamstrings",
        equipment: "Machine",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 75,
        lastWeight: 30,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "Knee-flexion work complements the hip-hinge pattern.",
        variants: [
          variant("Lying Leg Curl", "Hamstring curl", "Machine", "low"),
          variant("Single-Leg Curl", "Unilateral hamstrings", "Machine", "low"),
        ],
      }),
      exercise({
        id: "seated-calf-raise",
        name: "Seated Calf Raise",
        target: "Soleus",
        movement: "Plantar flexion",
        focus: "Bent-knee calves",
        equipment: "Machine",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 60,
        lastWeight: 35,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "Bent-knee position gives the soleus dedicated volume.",
        variants: [
          variant("Standing Calf Raise", "Gastrocnemius", "Machine", "low"),
          variant("Leg Press Calf Raise", "Calves · loaded", "Machine", "low"),
        ],
      }),
      exercise({
        id: "hanging-knee-raise",
        name: "Hanging Knee Raise",
        target: "Abs",
        secondary: ["Hip flexors"],
        movement: "Spinal flexion",
        focus: "Lower abs · pelvic control",
        equipment: "Bodyweight",
        sets: 3,
        repMin: 10,
        repMax: 15,
        rest: 45,
        lastWeight: 0,
        kind: "isolation",
        goal: "hypertrophy",
        reason: "Dynamic trunk flexion follows the heavy lower-body work.",
        variants: [
          variant("Lying Leg Raise", "Lower abs", "Bodyweight", "low"),
          variant("Cable Crunch", "Loaded abs", "Cable", "low"),
        ],
      }),
      exercise({
        id: "cable-wood-chop",
        name: "Cable Wood Chop",
        target: "Obliques",
        movement: "Trunk rotation",
        focus: "Anti-rotation control",
        equipment: "Cable",
        sets: 2,
        repMin: 10,
        repMax: 14,
        rest: 45,
        lastWeight: 12.5,
        kind: "isolation",
        goal: "joint relief",
        reason: "Two controlled sets add rotational core work within the 90-minute cap.",
        variants: [
          variant("Side Plank", "Lateral core stability", "Bodyweight", "low"),
          variant("Pallof Press", "Anti-rotation core", "Cable", "low"),
        ],
      }),
    ],
  },
];

export const restDay: WorkoutDay = {
  key: "sunday",
  day: "Sunday",
  shortDay: "S",
  title: "Rest + Recover",
  focus: "Walk · hydrate · prepare",
  duration: 0,
  intensity: "Recovery",
  warmup: [],
  exercises: [],
};

export const fullWeek = [...workoutPlan, restDay];

export function getTodayWorkout(date = new Date()) {
  const index = date.getDay();
  return index === 0 ? restDay : workoutPlan[index - 1];
}

export const volumeTrend = [
  { week: "W1", volume: 8560, baseline: 8200 },
  { week: "W2", volume: 9120, baseline: 8400 },
  { week: "W3", volume: 8940, baseline: 8600 },
  { week: "W4", volume: 9680, baseline: 8800 },
  { week: "W5", volume: 10240, baseline: 9000 },
  { week: "W6", volume: 10780, baseline: 9200 },
];

export const weightTrend = [
  { date: "May 25", weight: 61.7 },
  { date: "Jun 1", weight: 61.9 },
  { date: "Jun 8", weight: 62.2 },
  { date: "Jun 15", weight: 62.35 },
  { date: "Jun 22", weight: 62.6 },
  { date: "Jun 29", weight: 62.8 },
  { date: "Jul 6", weight: 63.0 },
];

export const strengthTrend = [
  { month: "Feb", press: 18, row: 35, rdl: 35 },
  { month: "Mar", press: 20, row: 37.5, rdl: 40 },
  { month: "Apr", press: 20, row: 40, rdl: 42.5 },
  { month: "May", press: 22, row: 42.5, rdl: 45 },
  { month: "Jun", press: 24, row: 45, rdl: 50 },
];

export const muscleVolume = [
  { muscle: "Chest", sets: 31, target: 28 },
  { muscle: "Back", sets: 34, target: 32 },
  { muscle: "Delts", sets: 18, target: 18 },
  { muscle: "Arms", sets: 25, target: 24 },
  { muscle: "Legs", sets: 20, target: 20 },
  { muscle: "Core", sets: 5, target: 6 },
];

export const recentRecords = [
  { exercise: "Incline DB Press", result: "24 kg × 10", gain: "+2 reps", date: "Jul 3" },
  { exercise: "Romanian Deadlift", result: "50 kg × 8", gain: "+5 kg", date: "Jun 28" },
  { exercise: "Seated Cable Row", result: "45 kg × 12", gain: "+2.5 kg", date: "Jun 24" },
  { exercise: "Leg Press", result: "100 kg × 11", gain: "+1 rep", date: "Jun 21" },
];

export const bodyMetrics = [
  { label: "Body weight", value: "63.0", unit: "kg", delta: "+1.3 kg" },
  { label: "Chest", value: "94.5", unit: "cm", delta: "+2.0 cm" },
  { label: "Waist", value: "76.0", unit: "cm", delta: "+0.2 cm" },
  { label: "Arms", value: "32.8", unit: "cm", delta: "+1.1 cm" },
  { label: "Thighs", value: "53.4", unit: "cm", delta: "+1.5 cm" },
  { label: "Shoulders", value: "111", unit: "cm", delta: "+2.4 cm" },
];

export const consistency = [
  0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1,
  1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
];

export function getLibraryExercises() {
  const exercises = workoutPlan.flatMap((day) =>
    day.exercises.map((item) => ({
      ...item,
      day: day.day,
      dayTitle: day.title,
    })),
  );

  return [...new Map(exercises.map((item) => [item.id, item])).values()];
}
